### ISSUE TITLE
[BUG] publish 命令的--wiki和--no-library参数问题

### ISSUE THREAD

**Issue by oflg** [tiddly-gittly/plugin-dev-cli#3]
1. publish 命令的 --wiki 问题

把模板里的 wiki 文件夹改为 wikiname 后，运行 `tiddlywiki-plugin-dev publish  --wiki ./wikiname --offline `会报错。

![image](https://user-images.githubusercontent.com/42492105/212073905-5c96d195-4bd2-4039-9a58-e6b795000622.png)

并且经测试只要项目目录里有 wiki 这个文件夹，就算 `--wiki ./wikiname` 也不会报错。

2. publish 命令的 --no-library 问题

加上这个参数后，构建出的 html 里不包含任何 src 目录里的插件。

（不知道是不是我理解错了，还是bug。我理解正常的功能是html里包含插件，加上这个参数后只是不生成library了。）

**Comment by Gk0Wk** [comment]
看看两个问题有没有修复(0.0.33)

**Comment by oflg** [comment]
谢谢！修复了。
